game_ideation_task:
  description: >
    Create a new innovative and engaging game idea for a browser game titled: {game_title}
    You are allowed to use any tools available to you to help you create the game idea.
  expected_output: >
    A game concept brief to be given to the game designer. It should include:
    - Game title
    - a short idea description in 2 to 3 sentences.
    - description of the core idea
    - a list of key features and mechanics
  agent: game_creative_strategist
  output_file: output/{game_title}/game_ideation.md
  markdown: true

game_design_task:
  description: >
    Design a browser game titled: {game_title}
    An ideation document has been provided to you. Use it to help you design the game.
  expected_output: >
    A game design document. It should include:
    - Game title
    - a short idea description in 2 to 3 sentences.
    - description of the core idea
    - breakdown of the game mechanics and features
    - breakdown of the game art and design
  agent: game_designer
  output_file: output/{game_title}/game_design.md
  markdown: true